// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using spieleliste_backend.Data;

namespace spieleliste_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190910204419_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("spieleliste_backend.Models.ListenEintrag", b =>
                {
                    b.Property<int>("SpielId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SpielId");

                    b.ToTable("ListenEintraege");
                });
#pragma warning restore 612, 618
        }
    }
}
